INSERT INTO CATEGORY_ENTITY (ID_CATEGORY,CODE_CATEGORY,NAME_CATEGORY) VALUES (1,'SNK','Sneakers');
INSERT INTO CATEGORY_ENTITY (ID_CATEGORY,CODE_CATEGORY,NAME_CATEGORY) VALUES (2,'JKT','Jackets');

INSERT INTO PRODUCT_ENTITY (ID_PRODUCT,NAME_PRODUCT,DESC_PRODUCT,PRICE,CURRENCY,CATEGORY_ID_CATEGORY) VALUES
(1,'Sneakers ZX','A good Sneakers',10,'EUR',1);
INSERT INTO PRODUCT_ENTITY (ID_PRODUCT,NAME_PRODUCT,DESC_PRODUCT,PRICE,CURRENCY,CATEGORY_ID_CATEGORY) VALUES
(2,'Sneakers ZX2','new version',12.5,'EUR',1);
INSERT INTO PRODUCT_ENTITY (ID_PRODUCT,NAME_PRODUCT,DESC_PRODUCT,PRICE,CURRENCY,CATEGORY_ID_CATEGORY) VALUES
(3,'Jacket Base','Simple Jacket',10,'EUR',2);